WidgetApp update
Projekt-zespolowy-TIU/DesignYourNetwork pull request #14
Opened 2020-05-11 12:49 UTC by Flaysen

2020-05-11 14:15 UTC, Mat3oo requested changes

2020-05-11 14:15 UTC, Mat3oo commented on src/widgetApp/mainwindow.cpp
> +#include <QtCore>
Kolejność includów - [clang-tidy](https://llvm.org/docs/CodingStandards.html#include-style)
w naszym projekcie:
1. Main Module Header
2. System #includes
3. Local/Private Headers

```suggestion
#include "mainwindow.h"
#include "ui_mainwindow.h"

#include <QSpinBox>
#include <QLabel>
#include <QtCore>

#include "IPv4parser.h"
#include "SubnetsCalculatorV4.h"
#include "IPstructs.h"
```

2020-05-11 14:15 UTC, Mat3oo commented on src/widgetApp/mainwindow.cpp
> +    isHorizontal = false;
Wszystkie default'owe inicjalizacje należy/można umieścić w deklaracji klasy (header).

2020-05-11 14:15 UTC, Mat3oo commented on src/widgetApp/mainwindow.cpp
> +    spinBoxList = new QList<QSpinBox*>();
Sprawdzić, czy to możliwy wyciek pamięci.

2020-05-11 14:15 UTC, Mat3oo commented on src/widgetApp/mainwindow.cpp
> +    QString routerButtonText = QString::fromStdString("R" + std::to_string(1));
Możliwe uproszczenie:
`QString routerButtonText = QString{"R"} += '1';`
albo
`QString routerButtonText = QString{"R"} += 1;`
?

2020-05-11 14:15 UTC, Mat3oo commented on src/widgetApp/mainwindow.cpp
> +                                      "Host number: " + std::to_string((int)subnets.at(i)->HostNumber)));
Preferowane używanie static_cast<>(), zamiast C-style casting - [cppref](https://en.cppreference.com/w/cpp/language/static_cast)
```suggestion
        QLabel *hostLabel = new QLabel(QString::fromStdString(
                                      "Host number: " + std::to_string(static_cast<int>(subnets.at(i)->HostNumber))));
```

2020-05-11 14:15 UTC, Mat3oo commented on src/widgetApp/mainwindow.cpp
> +         QString subButtonText = QString::fromStdString("S" + std::to_string(1 + i));
`QString subButtonText = QString{"S"} + (1 + i);`
możliwe?
Jeżeli tak to reszta wystąpień również.

2020-05-11 14:15 UTC, Mat3oo commented on src/widgetApp/mainwindow.h
> +#include <QLayout>
To samo co w cpp.

2020-05-11 14:15 UTC, Mat3oo commented on src/widgetApp/mainwindow.h
> +        int subnetCount;
`int subnetCount = 0;`
Default initialization.

2020-05-11 14:15 UTC, Mat3oo commented on src/widgetApp/mainwindow.h
> +        SubnetsCalculatorV4 *calculator;
Value semantic:
`Networkv4 mainNetwork;`
 `SubnetsCalculatorV4 calculator;`

2020-05-11 14:15 UTC, Mat3oo commented on src/widgetApp/mainwindow.h
> +        QList<QSpinBox*> *spinBoxList;
Jeżeli Qt w jakiś sposób nie zarządza pamięcią, to trzeba pozbyć się tych wycieków pamięci.

2020-05-11 14:15 UTC, Mat3oo commented on src/widgetApp/mainwindow.h
> +        void initializeData();
Jeżeli inicjalizujesz wszytko w deklaracji, to jest to zbędna funkcja.

2020-05-11 14:15 UTC, Mat3oo commented on src/widgetApp/mainwindow.cpp
> +    calculator = new SubnetsCalculatorV4();
Niepotrzebne przy typach wartościowych.

2020-05-12 18:16 UTC, Mat3oo commented on src/widgetApp/mainwindow.cpp
> +                          binaryMaskWidget);
get - jest metodą shared_ptr, nie ma potrzeby pobierania wskaźnika.
Ip i Net mask są shared_ptr, więc wystarczy je zdereferować, tak samo jak w `line 289`
```suggestion
     displayInputInBinary(mainNetwork.Ip->asStringBin(),
                          binaryAddressWidget);

     displayInputInBinary(mainNetwork.NetMask->asStringBin(),
                          binaryMaskWidget);
```

2020-05-12 18:22 UTC, Flaysen commented on src/widgetApp/mainwindow.cpp
> +    QString routerButtonText = QString::fromStdString("R" + std::to_string(1));
na razie mamy jeden ruter więc nie ma sensu inkrementować

2020-05-12 18:25 UTC, Mat3oo commented on src/widgetApp/mainwindow.cpp
> +    QString routerButtonText = QString::fromStdString("R" + std::to_string(1));
W tym przykładzie zastanawiałem się czy można się pozbyć `QString::fromStdString` przez konkatenację (Q)stringów ;D

2020-05-12 18:34 UTC, Mat3oo commented on src/widgetApp/mainwindow.cpp
> +    spinBoxList = new QList<QSpinBox*>();
Potwierdzam tu wyciek pamięci - `spinBoxList = new QList<QSpinBox*>();`

2020-05-12 18:46 UTC, Mat3oo commented on src/widgetApp/mainwindow.h
> +        QList<QSpinBox*> *spinBoxList;
Jeżeli uważnie pisane to nie powinno być leaków:
- https://stackoverflow.com/questions/33508162/does-this-code-provide-memory-leaks
- https://stackoverflow.com/a/33508464/9889714

2020-05-13 13:48 UTC, Mat3oo commented on src/widgetApp/mainwindow.h
> +        QList<QSpinBox*> *spinBoxList;
```suggestion
        QList<QSpinBox*> spinBoxList;
```

2020-05-13 14:03 UTC, Mat3oo commented on src/widgetApp/mainwindow.cpp
> +         QString subButtonText = QString::fromStdString("S" + std::to_string(1 + i));
```suggestion
         QString subButtonText = QString{'S'} + QString::number{1 + i};
```

2020-05-31 19:42 UTC, Mat3oo approved these changes

2020-05-31 19:52 UTC, merged